"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var sucursalVeterinaria_1 = require("./sucursales/sucursalVeterinaria");
var veterinaria_1 = require("./veterinas/veterinaria");
var proveedor_1 = require("./proveedores/proveedor");
var suc01 = new sucursalVeterinaria_1.SucursalVeterinaria("San Expedito", "Pedito 123");
var vet01 = new veterinaria_1.Veterinaria("lucecita", "lucecita 222");
var prov01 = new proveedor_1.Proveedor("la mejor pasta base", "2983555666");
suc01.agregarVeterinaria();
suc01.agregarProveedor();
suc01.agregarCliente();
suc01.altaPaciente();
suc01.modificarVeterinaria();
suc01.modificarProveedor();
suc01.modificarCliente();
suc01.modificarPacientes();
suc01.eliminarVeterinaria();
suc01.eliminarProveedor();
suc01.eliminarCliente();
suc01.bajaPaciente();
