"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var sucursalVeterinaria_1 = require("./sucursales/sucursalVeterinaria");
var veterinaria_1 = require("./veterinas/veterinaria");
var cliente_1 = require("./clientes/cliente");
var proveedor_1 = require("./proveedores/proveedor");
var paciente_1 = require("./pacientes/paciente");
var suc01 = new sucursalVeterinaria_1.SucursalVeterinaria("San Expedito", "Pedito 123");
var vet01 = new veterinaria_1.Veterinaria("lucecita", "lucecita 222");
var prov01 = new proveedor_1.Proveedor("", "");
var cli01 = new cliente_1.Cliente(0, "", "");
var paci01 = new paciente_1.Paciente();
suc01.agregarVeterinaria();
suc01.agregarProveedor();
suc01.agregarCliente();
suc01.altaPaciente();
vet01.id;
cli01.idCliente;
